//! Host-side plugin runtime.
//!
//! This manages loaded WASM plugins and routes messages between the editor
//! and plugins. For now this is a stub that defines the interface - actual
//! WASM loading requires wasmtime or wasmer as a dependency.

use super::messages::*;
use std::collections::VecDeque;

/// Represents a loaded plugin.
pub struct PluginInstance {
    pub id: String,
    pub name: String,
    /// Messages queued from host to plugin
    pub inbox: VecDeque<Vec<u8>>,
    /// Messages received from plugin
    pub outbox: VecDeque<Vec<u8>>,
    /// Commands registered by this plugin
    pub commands: Vec<CommandRegister>,
}

/// The plugin host manages all loaded plugins.
pub struct PluginHost {
    plugins: Vec<PluginInstance>,
}

impl PluginHost {
    pub fn new() -> Self {
        Self {
            plugins: Vec::new(),
        }
    }

    /// Notify all plugins that a file was opened.
    pub fn notify_file_opened(&mut self, path: &str, language: &str, content: &str) {
        let payload = serde_json::to_vec(&FileOpened {
            path: path.into(),
            language: language.into(),
            content: content.into(),
        }).unwrap();
        let msg = encode_message(MSG_FILE_OPENED, &payload);
        for plugin in &mut self.plugins {
            plugin.inbox.push_back(msg.clone());
        }
    }

    /// Notify all plugins that a file was saved.
    pub fn notify_file_saved(&mut self, path: &str) {
        let payload = serde_json::to_vec(&FileSaved { path: path.into() }).unwrap();
        let msg = encode_message(MSG_FILE_SAVED, &payload);
        for plugin in &mut self.plugins {
            plugin.inbox.push_back(msg.clone());
        }
    }

    /// Notify all plugins that a file was closed.
    pub fn notify_file_closed(&mut self, path: &str) {
        let payload = serde_json::to_vec(&FileClosed { path: path.into() }).unwrap();
        let msg = encode_message(MSG_FILE_CLOSED, &payload);
        for plugin in &mut self.plugins {
            plugin.inbox.push_back(msg.clone());
        }
    }

    /// Collect outgoing messages from all plugins and process them.
    pub fn poll(&mut self) -> Vec<HostEvent> {
        let mut events = Vec::new();
        for plugin in &mut self.plugins {
            while let Some(msg_data) = plugin.outbox.pop_front() {
                if let Some((msg_type, payload)) = decode_message(&msg_data) {
                    match msg_type {
                        MSG_DIAGNOSTIC_UPDATE => {
                            if let Ok(update) = serde_json::from_slice::<DiagnosticUpdate>(payload) {
                                events.push(HostEvent::DiagnosticUpdate(update));
                            }
                        }
                        MSG_STATUS_UPDATE => {
                            if let Ok(status) = serde_json::from_slice::<StatusUpdate>(payload) {
                                events.push(HostEvent::StatusUpdate(status));
                            }
                        }
                        MSG_COMMAND_REGISTER => {
                            if let Ok(cmd) = serde_json::from_slice::<CommandRegister>(payload) {
                                plugin.commands.push(cmd.clone());
                                events.push(HostEvent::CommandRegistered(cmd));
                            }
                        }
                        MSG_COMPLETION_RESPONSE => {
                            if let Ok(resp) = serde_json::from_slice::<CompletionResponse>(payload) {
                                events.push(HostEvent::CompletionResponse(resp));
                            }
                        }
                        _ => {}
                    }
                }
            }
        }
        events
    }

    /// Get all registered commands from all plugins.
    pub fn all_commands(&self) -> Vec<&CommandRegister> {
        self.plugins.iter().flat_map(|p| p.commands.iter()).collect()
    }
}

/// Events generated by plugins for the host/editor to handle.
#[derive(Debug)]
pub enum HostEvent {
    DiagnosticUpdate(DiagnosticUpdate),
    StatusUpdate(StatusUpdate),
    CommandRegistered(CommandRegister),
    CompletionResponse(CompletionResponse),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn host_notifies_plugins() {
        let mut host = PluginHost::new();
        // No plugins loaded, should not crash
        host.notify_file_opened("test.rs", "rust", "fn main() {}");
        host.notify_file_saved("test.rs");
        host.notify_file_closed("test.rs");
        let events = host.poll();
        assert!(events.is_empty());
    }

    #[test]
    fn plugin_message_roundtrip() {
        let mut host = PluginHost::new();
        host.plugins.push(PluginInstance {
            id: "test-plugin".into(),
            name: "Test Plugin".into(),
            inbox: VecDeque::new(),
            outbox: VecDeque::new(),
            commands: Vec::new(),
        });

        // Simulate plugin sending a status update
        let payload = serde_json::to_vec(&StatusUpdate {
            text: "Indexing...".into(),
        }).unwrap();
        let msg = encode_message(MSG_STATUS_UPDATE, &payload);
        host.plugins[0].outbox.push_back(msg);

        let events = host.poll();
        assert_eq!(events.len(), 1);
        match &events[0] {
            HostEvent::StatusUpdate(s) => assert_eq!(s.text, "Indexing..."),
            _ => panic!("Expected StatusUpdate"),
        }
    }
}
