import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const widgetPage = (id: string) => `widgets/widget-pages/${id}`;

const layoutWidgets = [
  'absolute-fill',
  'align',
  'aspect-ratio',
  'center',
  'clip',
  'column',
  'composite',
  'container',
  'grid',
  'grid-item',
  'h-stack',
  'layout-builder',
  'lazy-column',
  'overlay',
  'positioned',
  'row',
  'safe-area',
  'scroll',
  'simple-grid',
  'spacer',
  'split-direction',
  'split-view',
  'transform',
  'v-stack',
  'wrap',
  'z-stack',
].map(widgetPage);

const inputWidgets = [
  'button',
  'button-content-align',
  'button-variant',
  'checkbox',
  'combobox',
  'date-picker',
  'date-range-picker',
  'drag-target',
  'draggable',
  'drop-down',
  'dropzone',
  'editable',
  'file-upload',
  'form-control',
  'gesture-detector',
  'number-input',
  'radio',
  'range-slider',
  'segmented-control',
  'select',
  'select-item',
  'slider',
  'switch',
  'text-input',
  'time-picker',
].map(widgetPage);

const overlayWidgets = [
  'accordion',
  'accordion-item',
  'breadcrumb',
  'breadcrumb-item',
  'drawer',
  'drawer-side',
  'flyout',
  'focus-scope',
  'hero',
  'menu',
  'menu-button',
  'menu-item',
  'modal',
  'modal-action',
  'pagination',
  'popover',
  'portal',
  'route',
  'route-params',
  'router',
  'tab-item',
  'tabs',
  'toast',
  'toast-kind',
  'tooltip',
  'transition',
].map(widgetPage);

const displayWidgets = [
  'alert',
  'alert-kind',
  'avatar',
  'badge',
  'calendar',
  'card',
  'circular-progress',
  'code',
  'data-table',
  'divider',
  'empty-state',
  'icon',
  'kbd',
  'link',
  'progress-bar',
  'rich-text',
  'rich-text-run',
  'skeleton',
  'spinner',
  'stat',
  'stepper',
  'table-column',
  'table-row',
  'tag',
  'text',
  'text-content',
  'text-font-style',
  'text-run-style',
  'timeline',
  'timeline-item',
  'tree-item',
  'tree-view',
].map(widgetPage);

const mediaWidgets = [
  'builder',
  'canvas',
  'canvas-lowerer',
  'custom-node',
  'image',
  'node',
  'terminal-launch-config',
  'terminal-session',
  'terminal-view',
  'video',
  'web-view',
].map(widgetPage);

const sidebars: SidebarsConfig = {
  referenceSidebar: [
    'overview/overview',
    {
      type: 'category',
      label: 'Core runtime',
      collapsed: false,
      items: [
        'core/widget-trait',
        'core/state-system',
        'core/rendering-pipeline',
        'core/commands-services-jobs',
        'core/resources-and-capabilities',
        'core/environment-input-and-ime',
        'core/animations-portals-media',
        'core/theming-and-i18n',
        'core/platform-runtime',
        'core/testing-and-diagnostics',
      ],
    },
    {
      type: 'category',
      label: 'Shells, targets, and tooling',
      collapsed: false,
      items: [
        'platform/targets',
        'platform/accessibility-and-i18n',
        'platform/testing',
        'cli/overview',
      ],
    },
    {
      type: 'category',
      label: 'Widgets',
      collapsed: false,
      items: [
        'widgets/catalog',
        'widgets/layout',
        'widgets/inputs',
        'widgets/overlays-and-navigation',
        'widgets/display-and-data',
        'widgets/media',
        {
          type: 'category',
          label: 'Layout and structure',
          collapsed: true,
          items: layoutWidgets,
        },
        {
          type: 'category',
          label: 'Forms and input',
          collapsed: true,
          items: inputWidgets,
        },
        {
          type: 'category',
          label: 'Navigation and overlays',
          collapsed: true,
          items: overlayWidgets,
        },
        {
          type: 'category',
          label: 'Display and feedback',
          collapsed: true,
          items: displayWidgets,
        },
        {
          type: 'category',
          label: 'Media and escape hatches',
          collapsed: true,
          items: mediaWidgets,
        },
      ],
    },
  ],
};

export default sidebars;
