import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const widgetPage = (id: string) => `widgets/widget-pages/${id}`;

const layoutWidgets = [
  'absolute-fill',
  'align',
  'aspect-ratio',
  'center',
  'clip',
  'column',
  'composite',
  'container',
  'grid',
  'grid-item',
  'h-stack',
  'layout-builder',
  'lazy-column',
  'overlay',
  'positioned',
  'row',
  'safe-area',
  'scroll',
  'simple-grid',
  'spacer',
  'split-direction',
  'split-view',
  'transform',
  'v-stack',
  'wrap',
  'z-stack',
].map(widgetPage);

const inputWidgets = [
  'button',
  'button-content-align',
  'button-variant',
  'checkbox',
  'combobox',
  'date-picker',
  'date-range-picker',
  'drag-target',
  'draggable',
  'drop-down',
  'dropzone',
  'editable',
  'file-upload',
  'form-control',
  'gesture-detector',
  'number-input',
  'radio',
  'range-slider',
  'segmented-control',
  'select',
  'select-item',
  'slider',
  'switch',
  'text-input',
  'time-picker',
].map(widgetPage);

const overlayWidgets = [
  'accordion',
  'accordion-item',
  'breadcrumb',
  'breadcrumb-item',
  'drawer',
  'drawer-side',
  'flyout',
  'focus-scope',
  'hero',
  'menu',
  'menu-button',
  'menu-item',
  'modal',
  'modal-action',
  'pagination',
  'popover',
  'portal',
  'route',
  'route-params',
  'router',
  'tab-item',
  'tabs',
  'toast',
  'toast-kind',
  'tooltip',
  'transition',
].map(widgetPage);

const displayWidgets = [
  'alert',
  'alert-kind',
  'avatar',
  'badge',
  'calendar',
  'card',
  'circular-progress',
  'code',
  'data-table',
  'divider',
  'empty-state',
  'icon',
  'kbd',
  'link',
  'progress-bar',
  'rich-text',
  'rich-text-run',
  'skeleton',
  'spinner',
  'stat',
  'stepper',
  'table-column',
  'table-row',
  'tag',
  'text',
  'text-content',
  'text-font-style',
  'text-run-style',
  'timeline',
  'timeline-item',
  'tree-item',
  'tree-view',
].map(widgetPage);

const mediaWidgets = [
  'builder',
  'canvas',
  'canvas-lowerer',
  'custom-node',
  'image',
  'node',
  'terminal-launch-config',
  'terminal-session',
  'terminal-view',
  'video',
  'web-view',
].map(widgetPage);

const chartFamilies = [
  { label: "3D and GL", items: ["charts/3d-and-gl/overview", "charts/3d-and-gl/bar3d-basic", "charts/3d-and-gl/bar3d-capacity", "charts/3d-and-gl/scene3d-bar-capacity", "charts/3d-and-gl/scene3d-scatter-clusters", "charts/3d-and-gl/scene3d-globe-coverage", "charts/3d-and-gl/scene3d-globe-status", "charts/3d-and-gl/graph3d-basic", "charts/3d-and-gl/bar3d-grid", "charts/3d-and-gl/scene3d-bar-grid", "charts/3d-and-gl/line3d-basic", "charts/3d-and-gl/scene3d-line-path", "charts/3d-and-gl/scene3d-mesh-field", "charts/3d-and-gl/graph3d-network", "charts/3d-and-gl/scene3d-network", "charts/3d-and-gl/scene3d-operations-bars", "charts/3d-and-gl/scene3d-scatter-outliers", "charts/3d-and-gl/scene3d-surface-response", "charts/3d-and-gl/scene3d-terrain-risk", "charts/3d-and-gl/scatter3d-basic", "charts/3d-and-gl/scatter3d-cluster", "charts/3d-and-gl/scatter3d-outliers", "charts/3d-and-gl/scene3d-service-cloud", "charts/3d-and-gl/line3d-spiral", "charts/3d-and-gl/scene3d-line-spiral", "charts/3d-and-gl/surface3d-basic", "charts/3d-and-gl/surface3d-terrain", "charts/3d-and-gl/scene3d-surface-terrain", "charts/3d-and-gl/graph3d-topology", "charts/3d-and-gl/scene3d-topology", "charts/3d-and-gl/line3d-trajectory", "charts/3d-and-gl/scene3d-volume-points", "charts/3d-and-gl/surface3d-wave", "charts/3d-and-gl/scene3d-surface-wave", "charts/3d-and-gl/scene3d-point-cloud-dense", "charts/3d-and-gl/point-cloud-dense", "charts/3d-and-gl/globe-basic", "charts/3d-and-gl/globe-coverage", "charts/3d-and-gl/globe-markers", "charts/3d-and-gl/mesh-surface", "charts/3d-and-gl/point-cloud", "charts/3d-and-gl/scene3d-point-cloud-sparse", "charts/3d-and-gl/point-cloud-sparse", "charts/3d-and-gl/terrain-surface", "charts/3d-and-gl/volume-style"] },
  { label: "Analytics", items: ["charts/analytics/overview", "charts/analytics/analytics-acquisition-line", "charts/analytics/analytics-gauge-score", "charts/analytics/analytics-channel-stack", "charts/analytics/analytics-cohort-heatmap", "charts/analytics/analytics-conversion-funnel", "charts/analytics/analytics-device-donut", "charts/analytics/analytics-calendar-engagement", "charts/analytics/analytics-route-engagement", "charts/analytics/analytics-treemap-features", "charts/analytics/analytics-journey-graph", "charts/analytics/analytics-journey-sankey", "charts/analytics/analytics-market-pie", "charts/analytics/analytics-sunburst-portfolio", "charts/analytics/analytics-radar-product", "charts/analytics/analytics-region-sales", "charts/analytics/analytics-toolbox-report", "charts/analytics/analytics-retention-area", "charts/analytics/analytics-segment-bubbles", "charts/analytics/analytics-parallel-segments", "charts/analytics/analytics-source-river"] },
  { label: "Bar", items: ["charts/bar/overview", "charts/bar/bar-benchmark-comparison", "charts/bar/bar-budget-stack", "charts/bar/bar-budget-variance", "charts/bar/bar-capacity", "charts/bar/bar-channel-stack", "charts/bar/bar-compact", "charts/bar/bar-customer-segments", "charts/bar/bar-diverging", "charts/bar/bar-funnel-units", "charts/bar/bar-grouped-quarter", "charts/bar/bar-kpi-background", "charts/bar/bar-negative-delta", "charts/bar/bar-performance-bands", "charts/bar/bar-pictorial-units", "charts/bar/bar-priority-queue", "charts/bar/bar-product-stack", "charts/bar/bar-profit-loss", "charts/bar/bar-quarter-waterfall", "charts/bar/bar-ranked", "charts/bar/bar-region-comparison", "charts/bar/bar-region-rank", "charts/bar/bar-retail-waterfall", "charts/bar/bar-return-deltas", "charts/bar/bar-rounded", "charts/bar/bar-sales-target-track", "charts/bar/bar-sla-breach-delta", "charts/bar/bar-small-multiples-a", "charts/bar/bar-small-multiples-b", "charts/bar/bar-sorted-horizontal", "charts/bar/bar-stacked-revenue", "charts/bar/bar-store-comparison", "charts/bar/bar-team-load", "charts/bar/bar-ticket-age", "charts/bar/bar-track-progress", "charts/bar/bar-utilization-capacity", "charts/bar/bar-waterfall", "charts/bar/bar-weekday-shape", "charts/bar/bar-wide-labels"] },
  { label: "Cartesian", items: ["charts/cartesian/overview", "charts/cartesian/line-area", "charts/cartesian/bar-background", "charts/cartesian/bar-basic", "charts/cartesian/line-basic", "charts/cartesian/bar-grouped", "charts/cartesian/bar-horizontal", "charts/cartesian/line-large", "charts/cartesian/pictorial-bar", "charts/cartesian/bar-negative", "charts/cartesian/line-smooth", "charts/cartesian/line-stacked-area", "charts/cartesian/bar-stacked", "charts/cartesian/line-step"] },
  { label: "Components and interaction", items: ["charts/components-and-interaction/overview", "charts/components-and-interaction/tooltip-axis", "charts/components-and-interaction/component-brush-horizontal", "charts/components-and-interaction/component-brush-rect", "charts/components-and-interaction/brush-select", "charts/components-and-interaction/data-zoom", "charts/components-and-interaction/component-data-zoom-long", "charts/components-and-interaction/component-data-zoom-short", "charts/components-and-interaction/component-graphic-band", "charts/components-and-interaction/component-graphic-callout", "charts/components-and-interaction/graphic-overlay", "charts/components-and-interaction/component-mark-area", "charts/components-and-interaction/mark-line-point", "charts/components-and-interaction/component-mark-line", "charts/components-and-interaction/component-mark-point", "charts/components-and-interaction/timeline-events", "charts/components-and-interaction/component-timeline-release", "charts/components-and-interaction/component-timeline-year", "charts/components-and-interaction/toolbox-actions", "charts/components-and-interaction/component-toolbox-full", "charts/components-and-interaction/component-toolbox-zoom", "charts/components-and-interaction/component-tooltip-axis", "charts/components-and-interaction/component-tooltip-item", "charts/components-and-interaction/component-visual-map"] },
  { label: "Coordinates", items: ["charts/coordinates/overview", "charts/coordinates/calendar-heatmap", "charts/coordinates/polar-bar", "charts/coordinates/polar-line", "charts/coordinates/single-axis"] },
  { label: "Data pipeline and interaction", items: ["charts/data-pipeline-and-interaction/overview", "charts/data-pipeline-and-interaction/dataset-encoded", "charts/data-pipeline-and-interaction/visual-map", "charts/data-pipeline-and-interaction/wordcloud"] },
  { label: "Dataset", items: ["charts/dataset/overview", "charts/dataset/dynamic-brush-telemetry", "charts/dataset/dataset-calendar-activity", "charts/dataset/dataset-map-coverage", "charts/dataset/dataset-visual-heatmap", "charts/dataset/dataset-filtered-pie", "charts/dataset/dataset-flow-sankey", "charts/dataset/dynamic-funnel-activation", "charts/dataset/dynamic-alert-scatter", "charts/dataset/dynamic-live-bars", "charts/dataset/dynamic-live-line", "charts/dataset/dynamic-radar-score", "charts/dataset/dynamic-status-gauge", "charts/dataset/dataset-product-trends", "charts/dataset/dataset-products-by-year", "charts/dataset/dataset-parallel-quality", "charts/dataset/dynamic-timeline-quarters", "charts/dataset/dataset-ranked-bars", "charts/dataset/dataset-risk-bubbles", "charts/dataset/dataset-stacked-revenue", "charts/dataset/dynamic-toolbox-telemetry"] },
  { label: "Dataset and dynamic", items: ["charts/dataset-and-dynamic/overview", "charts/dataset-and-dynamic/dataset-stack-area", "charts/dataset-and-dynamic/dynamic-effect-alerts", "charts/dataset-and-dynamic/dynamic-brush-scatter", "charts/dataset-and-dynamic/dynamic-pictorial-units", "charts/dataset-and-dynamic/dynamic-polar-score", "charts/dataset-and-dynamic/dynamic-radar-health", "charts/dataset-and-dynamic/dynamic-funnel-sales", "charts/dataset-and-dynamic/dynamic-gauge-score", "charts/dataset-and-dynamic/dynamic-single-axis-events", "charts/dataset-and-dynamic/dynamic-gauge-speed", "charts/dataset-and-dynamic/dynamic-toolbox-line", "charts/dataset-and-dynamic/dataset-encoded-bars", "charts/dataset-and-dynamic/dataset-encoded-lines", "charts/dataset-and-dynamic/visual-map-calendar", "charts/dataset-and-dynamic/visual-map-heatmap", "charts/dataset-and-dynamic/visual-map-scatter"] },
  { label: "Geo", items: ["charts/geo/overview", "charts/geo/map-capacity-regions", "charts/geo/lines-courier-routes", "charts/geo/map-coverage-score", "charts/geo/geo-data-center-links", "charts/geo/geo-dispatch-routes", "charts/geo/map-expansion-plan", "charts/geo/lines-flight-density", "charts/geo/lines-incident-routing", "charts/geo/map-incident-severity", "charts/geo/map-market-regions", "charts/geo/geo-migration-flow", "charts/geo/geo-network-overlay", "charts/geo/lines-network-traffic", "charts/geo/map-risk-regions", "charts/geo/geo-route-overlay", "charts/geo/geo-sales-routes", "charts/geo/map-sales-territory", "charts/geo/map-service-health", "charts/geo/lines-supply-routes", "charts/geo/map-support-demand"] },
  { label: "Geo and route", items: ["charts/geo-and-route/overview", "charts/geo-and-route/lines-flight-like", "charts/geo-and-route/geo-network", "charts/geo-and-route/geo-migration", "charts/geo-and-route/map-region-values", "charts/geo-and-route/map-risk", "charts/geo-and-route/geo-route-arcs", "charts/geo-and-route/geo-route-map", "charts/geo-and-route/map-sales", "charts/geo-and-route/map-service-coverage", "charts/geo-and-route/lines-traffic"] },
  { label: "Geographic and route", items: ["charts/geographic-and-route/overview", "charts/geographic-and-route/map-choropleth", "charts/geographic-and-route/geo-lines", "charts/geographic-and-route/lines-basic", "charts/geographic-and-route/route-map"] },
  { label: "Heatmap", items: ["charts/heatmap/overview", "charts/heatmap/heatmap-access-matrix", "charts/heatmap/heatmap-availability-window", "charts/heatmap/calendar-commit-activity", "charts/heatmap/heatmap-correlation-grid", "charts/heatmap/calendar-retention-daily", "charts/heatmap/calendar-sales-daily", "charts/heatmap/visual-map-density-grid", "charts/heatmap/heatmap-deployment-hours", "charts/heatmap/heatmap-feature-usage", "charts/heatmap/calendar-incident-volume", "charts/heatmap/visual-map-load-grid", "charts/heatmap/calendar-quality-gates", "charts/heatmap/heatmap-queue-depth", "charts/heatmap/heatmap-regression-risk", "charts/heatmap/calendar-release-burndown", "charts/heatmap/heatmap-resource-saturation", "charts/heatmap/heatmap-service-risk", "charts/heatmap/heatmap-support-load", "charts/heatmap/calendar-user-activity", "charts/heatmap/visual-map-calendar-builds"] },
  { label: "Heatmap and calendar", items: ["charts/heatmap-and-calendar/overview", "charts/heatmap-and-calendar/heatmap-availability", "charts/heatmap-and-calendar/calendar-builds", "charts/heatmap-and-calendar/heatmap-correlation", "charts/heatmap-and-calendar/calendar-incidents", "charts/heatmap-and-calendar/heatmap-large-matrix", "charts/heatmap-and-calendar/calendar-quarter", "charts/heatmap-and-calendar/heatmap-resource-load", "charts/heatmap-and-calendar/calendar-retention", "charts/heatmap-and-calendar/heatmap-risk-grid", "charts/heatmap-and-calendar/heatmap-small-matrix", "charts/heatmap-and-calendar/visual-map-density", "charts/heatmap-and-calendar/heatmap-weekday-hour"] },
  { label: "Hierarchy", items: ["charts/hierarchy/overview", "charts/hierarchy/graph-alert-correlation", "charts/hierarchy/treemap-budget-allocation", "charts/hierarchy/theme-river-channel-mix", "charts/hierarchy/treemap-cost-centers", "charts/hierarchy/graph-customer-journey", "charts/hierarchy/sunburst-customer-segments", "charts/hierarchy/sankey-energy-balance", "charts/hierarchy/sunburst-feature-areas", "charts/hierarchy/tree-file-ownership", "charts/hierarchy/sankey-lead-flow", "charts/hierarchy/sunburst-org-revenue", "charts/hierarchy/tree-platform-modules", "charts/hierarchy/graph-platform-topology", "charts/hierarchy/tree-product-taxonomy", "charts/hierarchy/tree-radial-services", "charts/hierarchy/sankey-resolution-path", "charts/hierarchy/graph-service-dependencies", "charts/hierarchy/treemap-storage-classes", "charts/hierarchy/theme-river-support"] },
  { label: "Hierarchy and flow", items: ["charts/hierarchy-and-flow/overview", "charts/hierarchy-and-flow/treemap-budget", "charts/hierarchy-and-flow/graph-circular-like", "charts/hierarchy-and-flow/theme-river-demand", "charts/hierarchy-and-flow/graph-dependencies", "charts/hierarchy-and-flow/sankey-energy", "charts/hierarchy-and-flow/tree-file-system", "charts/hierarchy-and-flow/tree-org", "charts/hierarchy-and-flow/sunburst-product", "charts/hierarchy-and-flow/tree-radial-taxonomy", "charts/hierarchy-and-flow/sunburst-revenue", "charts/hierarchy-and-flow/graph-services", "charts/hierarchy-and-flow/treemap-storage", "charts/hierarchy-and-flow/theme-river-traffic", "charts/hierarchy-and-flow/sankey-user-flow"] },
  { label: "Interaction", items: ["charts/interaction/overview", "charts/interaction/interaction-toolbox-analysis", "charts/interaction/interaction-annotation-callout", "charts/interaction/interaction-tooltip-axis", "charts/interaction/interaction-mark-area-breach", "charts/interaction/interaction-brush-outliers", "charts/interaction/interaction-brush-region", "charts/interaction/interaction-timeline-capacity", "charts/interaction/interaction-datazoom-overview", "charts/interaction/interaction-marked-deploy", "charts/interaction/interaction-toolbox-export", "charts/interaction/interaction-graphic-band", "charts/interaction/interaction-graphic-note", "charts/interaction/interaction-tooltip-grouped", "charts/interaction/interaction-tooltip-item", "charts/interaction/interaction-marked-slo", "charts/interaction/interaction-toolbox-restore", "charts/interaction/interaction-select-scatter", "charts/interaction/interaction-datazoom-telemetry", "charts/interaction/interaction-timeline-releases", "charts/interaction/interaction-timeline-years"] },
  { label: "Line", items: ["charts/line/overview", "charts/line/line-alert-annotations", "charts/line/line-annotation", "charts/line/line-api-throughput", "charts/line/line-capacity-forecast", "charts/line/line-conversion-stack", "charts/line/line-demand-spark", "charts/line/line-spark-dense", "charts/line/line-deployment-events", "charts/line/line-dual-series", "charts/line/line-error-budget", "charts/line/line-forecast-band", "charts/line/line-gradient-area", "charts/line/line-inventory-end-step", "charts/line/line-alert-events", "charts/line/line-threshold", "charts/line/line-log-shaped", "charts/line/line-market-index", "charts/line/line-minmax-band", "charts/line/line-operational-steps", "charts/line/line-product-mix-area", "charts/line/line-quality-band", "charts/line/line-region-comparison", "charts/line/line-release-window", "charts/line/line-retention-window", "charts/line/line-revenue-seasonality", "charts/line/line-rolling-average", "charts/line/line-seasonal", "charts/line/line-service-latency", "charts/line/line-signup-cohorts", "charts/line/line-stacked-stream", "charts/line/line-step-end", "charts/line/line-step-start", "charts/line/line-support-volume", "charts/line/line-traffic-rolling-average", "charts/line/line-weekly-cycle", "charts/line/line-zoomed-window"] },
  { label: "Monitoring", items: ["charts/monitoring/overview", "charts/monitoring/monitoring-brush-investigation", "charts/monitoring/monitoring-capacity-gauge", "charts/monitoring/monitoring-dependency-graph", "charts/monitoring/monitoring-error-scatter", "charts/monitoring/monitoring-load-heatmap", "charts/monitoring/monitoring-3d-cloud", "charts/monitoring/monitoring-3d-grid", "charts/monitoring/monitoring-annotation", "charts/monitoring/monitoring-error-band", "charts/monitoring/monitoring-single-axis-events", "charts/monitoring/monitoring-overview-line", "charts/monitoring/monitoring-risk-radar", "charts/monitoring/monitoring-toolbox-analysis", "charts/monitoring/monitoring-traffic-bars", "charts/monitoring/monitoring-flow-sankey", "charts/monitoring/monitoring-region-map", "charts/monitoring/monitoring-route-lines", "charts/monitoring/monitoring-release-timeline", "charts/monitoring/monitoring-service-rank", "charts/monitoring/monitoring-uptime-calendar"] },
  { label: "Pie and radial", items: ["charts/pie-and-radial/overview", "charts/pie-and-radial/pie-area-rose", "charts/pie-and-radial/gauge-capacity", "charts/pie-and-radial/polar-cyclic-bar", "charts/pie-and-radial/pie-device-mix", "charts/pie-and-radial/pie-market-share", "charts/pie-and-radial/pie-nested-like", "charts/pie-and-radial/pie-rose-presentation", "charts/pie-and-radial/radar-profile-a", "charts/pie-and-radial/radar-profile-b", "charts/pie-and-radial/gauge-score", "charts/pie-and-radial/pie-two-level", "charts/pie-and-radial/polar-wind-line"] },
  { label: "Radial", items: ["charts/radial/overview", "charts/radial/gauge-availability", "charts/radial/gauge-build-confidence", "charts/radial/gauge-capacity-headroom", "charts/radial/polar-cycle-line", "charts/radial/gauge-deploy-health", "charts/radial/pie-device-donut", "charts/radial/pie-expense-donut", "charts/radial/pie-exposure-rose", "charts/radial/polar-hourly-load", "charts/radial/pie-market-rose", "charts/radial/pie-plan-share", "charts/radial/radar-platform-readiness", "charts/radial/radar-product-fit", "charts/radial/pie-revenue-mix", "charts/radial/pie-risk-rose", "charts/radial/polar-seasonality-bars", "charts/radial/radar-service-health", "charts/radial/pie-source-mix", "charts/radial/radar-team-balance", "charts/radial/polar-wind-speed"] },
  { label: "Radial and polar", items: ["charts/radial-and-polar/overview", "charts/radial-and-polar/pie-donut", "charts/radial-and-polar/radar-filled", "charts/radial-and-polar/gauge-basic", "charts/radial-and-polar/liquid-fill", "charts/radial-and-polar/pie-basic", "charts/radial-and-polar/gauge-progress", "charts/radial-and-polar/radar-basic", "charts/radial-and-polar/pie-rose-area", "charts/radial-and-polar/pie-rose-radius"] },
  { label: "Relationships and hierarchy", items: ["charts/relationships-and-hierarchy/overview", "charts/relationships-and-hierarchy/graph-force", "charts/relationships-and-hierarchy/funnel-basic", "charts/relationships-and-hierarchy/parallel-basic", "charts/relationships-and-hierarchy/tree-radial", "charts/relationships-and-hierarchy/sankey-basic", "charts/relationships-and-hierarchy/sunburst-basic", "charts/relationships-and-hierarchy/theme-river", "charts/relationships-and-hierarchy/tree-basic", "charts/relationships-and-hierarchy/treemap-basic"] },
  { label: "Scatter and statistical", items: ["charts/scatter-and-statistical/overview", "charts/scatter-and-statistical/candlestick-volume", "charts/scatter-and-statistical/funnel-conversion", "charts/scatter-and-statistical/single-axis-distribution", "charts/scatter-and-statistical/single-axis-events", "charts/scatter-and-statistical/candlestick-intraday", "charts/scatter-and-statistical/boxplot-latency", "charts/scatter-and-statistical/scatter-bubble-market", "charts/scatter-and-statistical/parallel-products", "charts/scatter-and-statistical/boxplot-quality", "charts/scatter-and-statistical/parallel-quality", "charts/scatter-and-statistical/funnel-recruiting", "charts/scatter-and-statistical/scatter-risk-return", "charts/scatter-and-statistical/scatter-clusters", "charts/scatter-and-statistical/scatter-outliers"] },
  { label: "Statistical", items: ["charts/statistical/overview", "charts/statistical/funnel-activation", "charts/statistical/scatter-alert-hotspots", "charts/statistical/boxplot-api-latency", "charts/statistical/candlestick-crypto-session", "charts/statistical/bubble-customer-value", "charts/statistical/parallel-device-quality", "charts/statistical/scatter-efficiency-frontier", "charts/statistical/candlestick-equity-session", "charts/statistical/single-axis-job-runtime", "charts/statistical/scatter-lab-samples", "charts/statistical/parallel-plan-comparison", "charts/statistical/scatter-portfolio-return", "charts/statistical/scatter-quality-outliers", "charts/statistical/boxplot-quality-spread", "charts/statistical/boxplot-region-spread", "charts/statistical/single-axis-release-events", "charts/statistical/scatter-risk-bubbles", "charts/statistical/parallel-risk-score", "charts/statistical/funnel-support-resolution", "charts/statistical/candlestick-volume-shift"] },
  { label: "Statistical and finance", items: ["charts/statistical-and-finance/overview", "charts/statistical-and-finance/boxplot-basic", "charts/statistical-and-finance/scatter-bubble", "charts/statistical-and-finance/candlestick-basic", "charts/statistical-and-finance/heatmap-cartesian", "charts/statistical-and-finance/scatter-effect", "charts/statistical-and-finance/scatter-basic"] },
];

const chartReferenceItems = chartFamilies.map((family) => ({
  type: 'category' as const,
  label: family.label,
  collapsed: true,
  items: family.items,
}));

const sidebars: SidebarsConfig = {
  referenceSidebar: [
    'overview/overview',
    {
      type: 'category',
      label: 'Core runtime',
      collapsed: false,
      items: [
        'core/widget-trait',
        'core/state-system',
        'core/rendering-pipeline',
        'core/commands-services-jobs',
        'core/resources-and-capabilities',
        'core/environment-input-and-ime',
        'core/animations-portals-media',
        'core/theming-and-i18n',
        'core/platform-runtime',
        'core/testing-and-diagnostics',
      ],
    },
    {
      type: 'category',
      label: 'Shells, targets, and tooling',
      collapsed: false,
      items: [
        'platform/targets',
        'platform/accessibility-and-i18n',
        'platform/testing',
        'cli/overview',
      ],
    },
    {
      type: 'category',
      label: 'Widgets',
      collapsed: false,
      items: [
        'widgets/catalog',
        'widgets/layout',
        'widgets/inputs',
        'widgets/overlays-and-navigation',
        'widgets/display-and-data',
        'widgets/media',
        {
          type: 'category',
          label: 'Layout and structure',
          collapsed: true,
          items: layoutWidgets,
        },
        {
          type: 'category',
          label: 'Forms and input',
          collapsed: true,
          items: inputWidgets,
        },
        {
          type: 'category',
          label: 'Navigation and overlays',
          collapsed: true,
          items: overlayWidgets,
        },
        {
          type: 'category',
          label: 'Display and feedback',
          collapsed: true,
          items: displayWidgets,
        },
        {
          type: 'category',
          label: 'Media and escape hatches',
          collapsed: true,
          items: mediaWidgets,
        },
      ],
    },

    {
      type: 'category',
      label: 'Charts',
      collapsed: false,
      items: ['charts/overview', ...chartReferenceItems],
    },
  ],
};

export default sidebars;
